/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValuesRouteImport } from './routes/values'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RanksRouteImport } from './routes/ranks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CloudNineRouteImport } from './routes/cloud-nine'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIdRouteImport } from './routes/trips_.$id'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as AdminTripsRouteImport } from './routes/admin_.trips'
import { Route as AdminRollcallRouteImport } from './routes/admin_.rollcall'
import { Route as AdminRegistrationsRouteImport } from './routes/admin_.registrations'
import { Route as AdminNotificationsRouteImport } from './routes/admin_.notifications'
import { Route as AdminGalleryRouteImport } from './routes/admin_.gallery'
import { Route as AdminExportsRouteImport } from './routes/admin_.exports'
import { Route as AdminCarpoolRouteImport } from './routes/admin_.carpool'
import { Route as AdminEventsIdRouteImport } from './routes/admin_.events.$id'

const ValuesRoute = ValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RanksRoute = RanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudNineRoute = CloudNineRouteImport.update({
  id: '/cloud-nine',
  path: '/cloud-nine',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/trips_/$id',
  path: '/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/admin_/trips',
  path: '/admin/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRollcallRoute = AdminRollcallRouteImport.update({
  id: '/admin_/rollcall',
  path: '/admin/rollcall',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin_/registrations',
  path: '/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin_/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/admin_/gallery',
  path: '/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportsRoute = AdminExportsRouteImport.update({
  id: '/admin_/exports',
  path: '/admin/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCarpoolRoute = AdminCarpoolRouteImport.update({
  id: '/admin_/carpool',
  path: '/admin/carpool',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/admin_/events/$id',
  path: '/admin/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cloud-nine': typeof CloudNineRoute
  '/community': typeof CommunityRoute
  '/gallery': typeof GalleryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/my-trips': typeof MyTripsRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/ranks': typeof RanksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/trips': typeof TripsRoute
  '/values': typeof ValuesRoute
  '/admin/carpool': typeof AdminCarpoolRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/rollcall': typeof AdminRollcallRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cloud-nine': typeof CloudNineRoute
  '/community': typeof CommunityRoute
  '/gallery': typeof GalleryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/my-trips': typeof MyTripsRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/ranks': typeof RanksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/trips': typeof TripsRoute
  '/values': typeof ValuesRoute
  '/admin/carpool': typeof AdminCarpoolRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/rollcall': typeof AdminRollcallRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cloud-nine': typeof CloudNineRoute
  '/community': typeof CommunityRoute
  '/gallery': typeof GalleryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/my-trips': typeof MyTripsRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/ranks': typeof RanksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/trips': typeof TripsRoute
  '/values': typeof ValuesRoute
  '/admin_/carpool': typeof AdminCarpoolRoute
  '/admin_/exports': typeof AdminExportsRoute
  '/admin_/gallery': typeof AdminGalleryRoute
  '/admin_/notifications': typeof AdminNotificationsRoute
  '/admin_/registrations': typeof AdminRegistrationsRoute
  '/admin_/rollcall': typeof AdminRollcallRoute
  '/admin_/trips': typeof AdminTripsRoute
  '/admin_/users': typeof AdminUsersRoute
  '/trips_/$id': typeof TripsIdRoute
  '/admin_/events/$id': typeof AdminEventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cloud-nine'
    | '/community'
    | '/gallery'
    | '/how-it-works'
    | '/my-trips'
    | '/passport'
    | '/profile'
    | '/ranks'
    | '/reset-password'
    | '/rules'
    | '/trips'
    | '/values'
    | '/admin/carpool'
    | '/admin/exports'
    | '/admin/gallery'
    | '/admin/notifications'
    | '/admin/registrations'
    | '/admin/rollcall'
    | '/admin/trips'
    | '/admin/users'
    | '/trips/$id'
    | '/admin/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cloud-nine'
    | '/community'
    | '/gallery'
    | '/how-it-works'
    | '/my-trips'
    | '/passport'
    | '/profile'
    | '/ranks'
    | '/reset-password'
    | '/rules'
    | '/trips'
    | '/values'
    | '/admin/carpool'
    | '/admin/exports'
    | '/admin/gallery'
    | '/admin/notifications'
    | '/admin/registrations'
    | '/admin/rollcall'
    | '/admin/trips'
    | '/admin/users'
    | '/trips/$id'
    | '/admin/events/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cloud-nine'
    | '/community'
    | '/gallery'
    | '/how-it-works'
    | '/my-trips'
    | '/passport'
    | '/profile'
    | '/ranks'
    | '/reset-password'
    | '/rules'
    | '/trips'
    | '/values'
    | '/admin_/carpool'
    | '/admin_/exports'
    | '/admin_/gallery'
    | '/admin_/notifications'
    | '/admin_/registrations'
    | '/admin_/rollcall'
    | '/admin_/trips'
    | '/admin_/users'
    | '/trips_/$id'
    | '/admin_/events/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CloudNineRoute: typeof CloudNineRoute
  CommunityRoute: typeof CommunityRoute
  GalleryRoute: typeof GalleryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MyTripsRoute: typeof MyTripsRoute
  PassportRoute: typeof PassportRoute
  ProfileRoute: typeof ProfileRoute
  RanksRoute: typeof RanksRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RulesRoute: typeof RulesRoute
  TripsRoute: typeof TripsRoute
  ValuesRoute: typeof ValuesRoute
  AdminCarpoolRoute: typeof AdminCarpoolRoute
  AdminExportsRoute: typeof AdminExportsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminRollcallRoute: typeof AdminRollcallRoute
  AdminTripsRoute: typeof AdminTripsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  TripsIdRoute: typeof TripsIdRoute
  AdminEventsIdRoute: typeof AdminEventsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/values': {
      id: '/values'
      path: '/values'
      fullPath: '/values'
      preLoaderRoute: typeof ValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranks': {
      id: '/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof RanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-nine': {
      id: '/cloud-nine'
      path: '/cloud-nine'
      fullPath: '/cloud-nine'
      preLoaderRoute: typeof CloudNineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips_/$id': {
      id: '/trips_/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/trips': {
      id: '/admin_/trips'
      path: '/admin/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/rollcall': {
      id: '/admin_/rollcall'
      path: '/admin/rollcall'
      fullPath: '/admin/rollcall'
      preLoaderRoute: typeof AdminRollcallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/registrations': {
      id: '/admin_/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/notifications': {
      id: '/admin_/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/gallery': {
      id: '/admin_/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/exports': {
      id: '/admin_/exports'
      path: '/admin/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/carpool': {
      id: '/admin_/carpool'
      path: '/admin/carpool'
      fullPath: '/admin/carpool'
      preLoaderRoute: typeof AdminCarpoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/events/$id': {
      id: '/admin_/events/$id'
      path: '/admin/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CloudNineRoute: CloudNineRoute,
  CommunityRoute: CommunityRoute,
  GalleryRoute: GalleryRoute,
  HowItWorksRoute: HowItWorksRoute,
  MyTripsRoute: MyTripsRoute,
  PassportRoute: PassportRoute,
  ProfileRoute: ProfileRoute,
  RanksRoute: RanksRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RulesRoute: RulesRoute,
  TripsRoute: TripsRoute,
  ValuesRoute: ValuesRoute,
  AdminCarpoolRoute: AdminCarpoolRoute,
  AdminExportsRoute: AdminExportsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminRollcallRoute: AdminRollcallRoute,
  AdminTripsRoute: AdminTripsRoute,
  AdminUsersRoute: AdminUsersRoute,
  TripsIdRoute: TripsIdRoute,
  AdminEventsIdRoute: AdminEventsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
